### ISSUE TITLE
红米AX6000，能否编译一个闭源驱动的版本。

### ISSUE THREAD

**Issue by 582911658** [miaoermua/CatWrt#13]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by miaoermua** [comment]
暂时没有计划编译测试基于，hanwckf 改款 [Immortalwrt](https://github.com/immortalwrt/immortalwrt) 闭源无线固件的计划，如果后续合并进主仓库会考虑做的。
