### ISSUE TITLE
[ Feature ] 考虑为红米AX6000固件增加SFTP功能

### ISSUE THREAD

**Issue by Kia678** [miaoermua/CatWrt#15]
add vsftpd openssh-sftp-server

**Comment by miaoermua** [comment]
可以有，看后续

**Comment by miaoermua** [comment]
https://github.com/miaoermua/CatWrt/search?p=3&q=sftp

其实是有的，早上赶事

**Comment by miaoermua** [comment]
[](url)

**Comment by Kia678** [comment]
> https://github.com/miaoermua/CatWrt/search?p=3&q=sftp
> 
> 其实是有的，早上赶事

![image](https://user-images.githubusercontent.com/85081567/232390911-37b7b374-2a56-433f-bc02-d8fd3398948a.png)

提示这个错误，你看一下

**Comment by Kia678** [comment]
麻烦看一下上面这个错误

**Comment by miaoermua** [comment]
> 麻烦看一下上面这个错误

更新列表了吗，在终端输入安装命令输出的内容发上来。

**Comment by miaoermua** [comment]
> > > 麻烦看一下上面这个错误
> > 
> > 
> > 更新列表了吗，在终端输入安装命令输出的内容发上来。
> 
> ![image](https://user-images.githubusercontent.com/85081567/239245554-8e840a54-5a0d-442d-a2fa-52a98c70ace1.png)
> 
> 你看看，要怎么解决SFTP的问题，红米AX6000固件下个版本能否集成SFTP功能

你压根就没用我的源。。。

**Comment by Kia678** [comment]
> > > > > > 麻烦看一下上面这个错误
> > > > > 
> > > > > 
> > > > > 更新列表了吗，在终端输入安装命令输出的内容发上来。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/85081567/239245554-8e840a54-5a0d-442d-a2fa-52a98c70ace1.png)
> > > > 你看看，要怎么解决SFTP的问题，红米AX6000固件下个版本能否集成SFTP功能
> > > 
> > > 
> > > 你压根就没用我的源。。。
> > 
> > 
> > 你的源在哪里看？怎么替换
> 
> https://www.miaoer.xyz/posts/network/catwrt-expand

谢谢，openssh-sftp-server 已经安装好了。红米AX6000固件下个版本能否内置openssh-sftp-serve进去？

**Comment by miaoermua** [comment]
不能要瘦身
