### ISSUE TITLE
catwrt-v22.12-ramips-mt7621-d-team_newifi-d2-initramfs-kernel 固件出现问题 

### ISSUE THREAD

**Issue by n-WN** [miaoermua/CatWrt#2]
配置好ip为192.168.1.1和pppoe后这时候重启设备 wan口设置就会恢复默认 lan也变回了默认设置192.168.1.4 这是否已经影响正常使用

**Comment by miaoermua** [comment]
kernel 只是临时固件，请下载 sq 分区固件在临时固件里上传更新就是完整

**Comment by miaoermua** [comment]
新三的 breed 可以直接刷 sq 分区的固件镜像，我可以不知道你的行不行，你现在只需要在临时固件里面更新一下 sq，这里博客是完全有写的
