### ISSUE TITLE
新路由3 CatWrt v22.12 缺少 USB 和 EXT4/EXFAT 支持

### ISSUE THREAD

**Issue by Redleaves5** [miaoermua/CatWrt#20]
### 问题: 
新路由3 CatWrt v22.12缺少USB和EXT4/EXFAT支持

### 能否复现: 
能

### 版本信息

设备: 新路由3 CatWrt v22.12

![image](https://github.com/miaoermua/CatWrt/assets/90406238/87d2c5fb-0136-46b3-a1a6-a9ebd6730787)

- [x] 我已按照规定格式编写，没有的内容或备注请删除
- [x] 我使用的是 CatWrt

**Comment by miaoermua** [comment]
需要自己添加，具体看 [博客](https://www.miaoer.xyz/posts/network/catwrt-expand)，默认不带因为会影响 2.4G 无线

**Comment by Redleaves5** [comment]
> 需要自己添加，具体看 [博客](https://www.miaoer.xyz/posts/network/catwrt-expand)，默认不带因为会影响 2.4G 无线

opkg install 安装了以下包：
![image](https://github.com/miaoermua/CatWrt/assets/90406238/342e0395-c7e5-4613-b4fe-8554d0f15778)
但是没有效果

**Comment by miaoermua** [comment]
> > 需要自己添加，具体看 [博客](https://www.miaoer.xyz/posts/network/catwrt-expand)，默认不带因为会影响 2.4G 无线
> 
> opkg install 安装了以下包：
> ![image](https://github.com/miaoermua/CatWrt/assets/90406238/342e0395-c7e5-4613-b4fe-8554d0f15778)
> 但是没有效果

需要先进行 opkg update，需要完整命令输出结果才能诊断

**Comment by miaoermua** [comment]
在新版添加了 kmod-fs-ext4，除了 exfat，其他都齐了

**Comment by miaoermua** [comment]
![dca2cbd06872e25d20508393c4727441](https://github.com/user-attachments/assets/937ff5e1-15fe-4066-a10d-3134dc32cdae)

已支持，所以关闭了，如有需要随时打开 issues 提问
