### ISSUE TITLE
Redmi AX6000 用uboot刷完 CatWrt-v23.7 mt798x Beta 无法点亮开机

### ISSUE THREAD

**Issue by Kia678** [miaoermua/CatWrt#22]
### 问题: 
Redmi AX6000 用uboot刷完 CatWrt-v23.7 mt798x Beta 无法点亮开机

### 能否复现: 
能

### 版本信息
[CatWrt-v23.7 mt798x Beta](https://github.com/miaoermua/CatWrt/releases/tag/v23.7-mt798x)

设备: Redmi AX6000

版本号: [CatWrt-v23.7 mt798x Beta](https://github.com/miaoermua/CatWrt/releases/tag/v23.7-mt798x)

- [x] 我已按照规定格式编写，没有的内容或备注请删除
- [x] 我使用的是 CatWrt

**Comment by miaoermua** [comment]
23.7 问题已立项修复

**Comment by Kia678** [comment]
大概什么时候修复？
