### ISSUE TITLE
支持 luci-app-natmap

### ISSUE THREAD

**Issue by jeremysun0324** [miaoermua/CatWrt#25]
### 提议
现在的 Catwrt 的最新版本貌似还不支持 luci-app-natmap （我使用的 x86_64 版本不支持）表现为安装后没有管理页面 希望在新的版本中对其支持（不确定这属不属于 bug 属于的话帮我挪下标签 qwq）

### 为什么要
用着更方便吧，毕竟可以直接用UI看到打洞来的ip和端口，不用对着命令行敲了

### 实例
![natmap-4](https://github.com/miaoermua/CatWrt/assets/81454513/e120bd79-4a58-46d0-bc7f-32f3765a087b)
(来自 Natmap Wiki)

**Comment by miaoermua** [comment]
https://github.com/DavBfr/luci-app-netmap/releases

**Comment by jeremysun0324** [comment]
这个是netmap啊 反馈的是natmap..

**Comment by jeremysun0324** [comment]
emmm?
