### ISSUE TITLE
建议在软件源里加入nfs的支持

### ISSUE THREAD

**Issue by fucktimi** [miaoermua/CatWrt#36]
### 提议
建议加入nfs相关的软件包，luci-app-nfs等。作为除了samba之外局域网共享的另一个选项。

### 为什么要
相比samba4，nfs效率更高一些，特别是局域网内看4k uhd等大型视频的时候，拖进度条的卡顿感更少。

### 实例

*例如别人固件或者视频中演示的效果*

**Comment by miaoermua** [comment]
请提供对应架构

**Comment by fucktimi** [comment]
> 请提供对应架构

就是最普通的x64，

**Comment by miaoermua** [comment]
回去看看，如果天气好的话

**Comment by fucktimi** [comment]
> https://github.com/miaoermua/CatWrt/releases/tag/v24.9

好耶，happy

**Comment by miaoermua** [comment]
> > https://github.com/miaoermua/CatWrt/releases/tag/v24.9
> 
> 好耶，happy

![{F5D85555-9AAA-A792-81F7-4C2C7CC3AD70}](https://github.com/user-attachments/assets/9b4ba46a-524b-4eb7-8ea7-dabd1a66f0f3)
