### ISSUE TITLE
软件源内增加ua3f软件包

### ISSUE THREAD

**Issue by sffool** [miaoermua/CatWrt#39]
### 提议
软件源内增加 ua3f 软件包

### 为什么要
ua3f 相比 ua2f 更好用

### 实例
https://github.com/SunBK201/UA3F

设备: 小米 ac2100
ua3f_0.4.0-1_mipsle-softfloat.ipk

**Comment by miaoermua** [comment]
作者貌似没写 Makefile，不能编译

**Comment by miaoermua** [comment]
而且可以直装
