### ISSUE TITLE
软件包ua2f增加控制面板

### ISSUE THREAD

**Issue by sffool** [miaoermua/CatWrt#40]
### 提议
软件包ua2f增加控制面板

### 为什么要
方便

### 实例
这个项目
https://github.com/lucikap/luci-app-ua2f

**Comment by miaoermua** [comment]
设备是什么

**Comment by sffool** [comment]
小米ac2100，mt7621

**Comment by miaoermua** [comment]
https://github.com/miaoermua/CatWrt/releases/tag/v24.9.mt7621
