### ISSUE TITLE
软件包搜索不到clash

### ISSUE THREAD

**Issue by Zoltan3057** [miaoermua/CatWrt#44]
### 你的设备

catwrt

### CatWrt_Version

None

### CatWrt_Arch

None

### 能否复现 BUG

None

### 最后确认

- [X] 我确认我的 BUG 来自 CatWrt，而不是其他 OpenWrt 固件
- [X] 我将遵守 CatWrt 开源社区规范，不将设备用为商业目的
- [X] 我已确认我的内容反馈内容的正确

**Comment by miaoermua** [comment]
没应用软件源

https://www.miaoer.xyz/posts/blog/cattools

https://www.miaoer.xyz/posts/network/catwrt-install-application

https://www.miaoer.xyz/posts/network/catwrt-applist
