### ISSUE TITLE
CatWrt 意外崩溃自动软重启

### ISSUE THREAD

**Issue by lovemilk2333** [miaoermua/CatWrt#45]
### 提供 BUG 问题日志

```markdown
见附件
```

### 关于这个问题 BUG 描述

正常使用 CatWrt (包含 Docker 和 IPv6), 运行一段时间不定期自动重启

[内核日志 | kernel log](https://github.com/user-attachments/files/17528914/kernel_20241025_154634.log)
[系统日志 | openwrt log](https://github.com/user-attachments/files/17528915/openwrt_20241025_154633.log)

### 你的设备

X86_64 	Default string Default string/Aptio CRB - Intel(R) Celeron(R) CPU J1800 @ 2.41GHz : 2C2T (CpuMark : 17934.797839 Scores

### CatWrt_Version
CatWrt.v23.8.x86_64 / OpenWrt R23.7.7 / LuCI Master (git-23.226.38647-7acf7ff)

### CatWrt_Arch

AMD64 (x86_64)

### 能否复现 BUG

偶尔能复现

### 最后确认

- [X] 我确认我的 BUG 来自 CatWrt，而不是其他 OpenWrt 固件
- [X] 我将遵守 CatWrt 开源社区规范，不将设备用为商业目的
- [X] 我已确认我的内容反馈内容的正确

**Comment by miaoermua** [comment]
建议使用 cattools 生成日志文件重新提交附件（会包括拨号信息自己寻找并处理），目前来看是 netfilter 炸了有可能是 netdata 导致的

**Comment by miaoermua** [comment]
如果你是 rtl 网卡可能是网卡驱动的问题

**Comment by miaoermua** [comment]
建议先卸载 netdata 试试看，看到貌似是内存回收失败的问题，上游有这个问题但是没有解决方案，可能是 netdata 的问题
