### ISSUE TITLE
有线/无线驱动解决计划

### ISSUE THREAD

**Issue by miaoermua** [miaoermua/CatWrt#7]
为响应大家对 CatWrt 更多应用范围，有需增加驱动的小伙伴，留言一下所需的有线无线的机型和芯片，针对 x86 和 ARM 版本的 CatWrt 扩展建议，wireless 系列请勿参与。

如格式: 无线 - 绿联 AC650M - RTL 8811CU

计划优先 x86 平台更新

目前已知 ARM 平台友善 R2s lan 口无法连接，wan 口可以，已经在跟进处理；英特尔系列 AP 模式目前已经测试成功(只能开启 2.4G)；能提供已经完成无线驱动应用的可以发下需要安装的软件包，这对项目帮助很大谢谢。

Tip: 软路由添加并不是为了主要的无线需求，而是为了实现如工位网络，如果想正经使用建议搭配支持 AP 模式的硬路由！

**Comment by jiangxin0867** [comment]
无线 - 腾达 AC650M - RTL 8811CU

**Comment by AEnjoy** [comment]
Those packages that are Intel AX210 needed:
kmod-iwlwifi wireless-regdb wireless-tools **iwlwifi-firmware-ax210** wpa-supplicant hostapd;

And the other Intel wireless firmware packages could be found at Luci-System-Packages-Research, typing iwlwifi.

**Comment by miaoermua** [comment]
> 

还有 kmod-cfg80211 和 kmod-mac80211

**Comment by miaoermua** [comment]
已有测试版体验 https://github.com/miaoermua/CatWrt/releases/tag/v23.2
还差无线驱动部分，将在最近完成并且推送公测版

**Comment by miaoermua** [comment]
目前已经完善部分驱动 https://github.com/miaoermua/CatWrt/commit/ae3bae4e8ea02c3d0e23c98d13a3b54c9ac17fc8

**Comment by LCW0NJUPT** [comment]
无线 - orangePi R1Plus - RTL 8821CU

**Comment by Rikkaawa** [comment]
无线 - 华硕ChromeBox CN62 - Intel AC 7260
